name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/step-python@v5
        with :
          python-version: 3.11

      - name: Install dependencies
      run:|
        python -m pip install --upgrade pip
        pip install -git push origin main
        r requirements.txt

      - name: Run tests
      run:|
        pytest --cov=app -v